feat(🦶):  added TypeCheck for if statement and tests
marcauberer/compiler-design-lecture-project-TINF22B6 pull request #55
Opened 2024-05-29 10:14 UTC by dolerich-hirnfiedler

2024-05-29 10:55 UTC, marcauberer requested changes

2024-05-29 10:55 UTC, marcauberer commented on src/main/java/com/auberer/compilerdesignlectureproject/sema/TypeChecker.java
> +    return new ExprResult(new Type(SuperType.TY_EMPTY));
This is not complete. Where do you check if the condition is a bool and things?

2024-06-03 14:51 UTC, dolerich-hirnfiedler commented
i have updated the `visitIf` method to include a check for boolean in braces

2024-06-03 15:37 UTC, marcauberer approved these changes
Thanks

2024-06-03 15:37 UTC, merged